In [1]:
import os
import pandas as pd
from ytmusicapi import YTMusic

In [2]:
yt = YTMusic('../headers_auth.json')
search_results = pd.DataFrame(yt.search("Shine on you crazy diamond"))
search_results.head(3)

,resultType,videoId,title,artists,album,duration,thumbnails,browseId,type,artist,year,author,itemCount,views
0,song,54W8kktFE_o,Shine On You Crazy Diamond (Parts I-V),"[{'name': 'Pink Floyd', 'id': 'UCO6LS_5W7vqG9m...","{'name': 'Wish You Were Here', 'id': 'MPREb_w7...",13:33,[{'url': 'https://lh3.googleusercontent.com/-x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,song,9pkh8zi_eic,Shine On You Crazy Diamond (Parts 1 - 7) [Edit...,"[{'name': 'Pink Floyd', 'id': 'UCO6LS_5W7vqG9m...","{'name': 'Echoes (The Best Of Pink Floyd)', 'i...",17:32,[{'url': 'https://lh3.googleusercontent.com/B4...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,song,nHER1RmSqA8,Shine On You Crazy Diamond,"[{'name': 'Pink Floyd', 'id': 'UCO6LS_5W7vqG9m...","{'name': 'Pulse (Live)', 'id': 'MPREb_dCMssyAc...",13:35,[{'url': 'https://lh3.googleusercontent.com/qa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
%%time

PLAYLIST_LIMIT=500
playlists = pd.DataFrame(yt.get_library_playlists(limit=PLAYLIST_LIMIT))
playlists

Wall time: 11.8 s

,title,playlistId,thumbnails,count
0,Your Likes,LM,[{'url': 'https://www.gstatic.com/youtube/medi...,NaN
1,'10s Electronic,RDCLAK5uy_lvnl-qLThmB2VUUwN33HvXwwCOesXrH1s,[{'url': 'https://lh3.googleusercontent.com/iN...,100
2,2020 Albums,PLWptjpDqazOzaFe2TUAPwytU_pyFMVBOh,[{'url': 'https://lh3.googleusercontent.com/Ms...,13
3,ADAS Spring,PLWptjpDqazOyeMKN81aSpU6UNEWZlbaiR,[{'url': 'https://lh3.googleusercontent.com/R2...,4
4,ambiant electro,PLWptjpDqazOzjaFOAlWV37AywCmro60ET,[{'url': 'https://lh3.googleusercontent.com/FD...,65
...,...,...,...,...
247,zzzz_all 6,PLWptjpDqazOyh08tZjD0SBzQbehN2PGrC,[{'url': 'https://lh3.googleusercontent.com/5r...,661
248,zzzz_thumbs_down,PLWptjpDqazOwUz2ci9ZEivIJ_4dNVx9v-,[{'url': 'https://lh3.googleusercontent.com/V6...,14
249,zzzz_thumbs_down 1,PLWptjpDqazOxj8cjCK6wF1KzhG1mT94vs,[{'url': 'https://lh3.googleusercontent.com/8U...,14
250,zzzz_thumbs_up,PLWptjpDqazOwbnb0x7ecV_RZWxJToctaF,[{'url': 'https://lh3.googleusercontent.com/U6...,547
251,zzzz_thumbs_up 1,PLWptjpDqazOwobQdOQliW2IllkDxAKeU-,[{'url': 'https://lh3.googleusercontent.com/ic...,449

In [6]:
%%time

PLAYLIST_SONG_LIMIT=10000
USER='Jake G'
REMOVE_DISLIKE = True
BACKUP_DIR  = './playlists/'
PLAYLIST_TSV_COLS = ['title', 'artist', 'album', 'likeStatus', 'duration', 'videoId', 'albumId', 'artistId']
METADATA_TSV = '_metadata.tsv'
METADATA_TSV_COLS = ['title','trackCount','duration','privacy','id']

metadata = []
for i, row in playlists.iterrows():   
    print('\n\n(%d/%d) Playlist: %s %s ' % (i+1, len(playlists), row['title'], 80*'*'))

    # Fetch playlist
    playlist_meta = yt.get_playlist(row['playlistId'], limit=PLAYLIST_SONG_LIMIT)
    playlist_meta.pop('thumbnails', None)
    tracks = playlist_meta.pop('tracks', None)
    metadata.append(playlist_meta)
    print(pd.DataFrame.from_dict(playlist_meta, orient='index'))
    if playlist_meta['trackCount'] == 0:
        print('Skipping: %s, due to zero tracks' % playlist_meta['title'])
        continue

    # Parse playlist tracks
    tracks = pd.DataFrame(tracks)
    if REMOVE_DISLIKE:
        try:
            tracks_disliked = tracks.loc[tracks['likeStatus'] == 'DISLIKE']
            if len(tracks_disliked) and playlist_meta['author']['name'] == USER:
                print('Removing %d tracks:\n%s' % (len(tracks_disliked), tracks_disliked['title']))
                yt.remove_playlist_items(playlist_meta['id'], tracks_disliked.to_dict('records'))  
                tracks = tracks.loc[tracks['likeStatus'] != 'DISLIKE']
        except Exception as e:
            print('\nFailed to remove dislikes...\n%s\n' % e) 

    tracks['artistId'] = tracks['artists'].dropna().apply(lambda x: x[0]['id']) # TODO handle > 1 artist
    tracks['artist'] = tracks['artists'].dropna().apply(lambda x: x[0]['name'])
    tracks['albumId'] = tracks['album'].dropna().apply(lambda x: x['id'])
    tracks['album'] = tracks['album'].dropna().apply(lambda x: x['name'])
    tracks = tracks[PLAYLIST_TSV_COLS]
    tracks.to_csv(os.path.join(BACKUP_DIR, '%s.tsv' % playlist_meta['title']), sep='\t', header=True)


metadata = pd.DataFrame(metadata)[METADATA_TSV_COLS]
metadata.to_csv(os.path.join(BACKUP_DIR, METADATA_TSV), sep='\t', header=True)

************************** (217/252) Playlist: zzz_seed_music_albums Part 12 ****************************************
                                                            0
id                         PLWptjpDqazOxucEO1dM_JN3xI0OsMpbP0
privacy                                               PRIVATE
title                           zzz_seed_music_albums Part 12
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             6+ hours
trackCount                                                344


**************************************** (218/252) Playlist: zzz_seed_music_albums Part 2 ****************************************
                                                            0
id                         PLWptjpDqazOzoAhOdU6OqL95mg1WLsMd8
privacy                                               PRIVATE
title                            zzz_seed_music_albums Part 2
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                            10+ hours
trackCount                                                760


**************************************** (219/252) Playlist: zzz_seed_music_albums Part 3 ****************************************
                                                            0
id                         PLWptjpDqazOzC-9i99rA47_YZL9ML2fn6
privacy                                               PRIVATE
title                            zzz_seed_music_albums Part 3
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                751


**************************************** (220/252) Playlist: zzz_seed_music_albums Part 4 ****************************************
                                                            0
id                         PLWptjpDqazOxc85XseTRt9sjBX5MARqkK
privacy                                               PRIVATE
title                            zzz_seed_music_albums Part 4
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             8+ hours
trackCount                                                902


**************************************** (221/252) Playlist: zzz_seed_music_albums Part 5 ****************************************
                                                            0
id                         PLWptjpDqazOxu9UeO4cwXJX0jV0eud8dO
privacy                                               PRIVATE
title                            zzz_seed_music_albums Part 5
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                820


**************************************** (222/252) Playlist: zzz_seed_music_albums Part 6 ****************************************
                                                            0
id                         PLWptjpDqazOzlOe8It6mAGkia1ZaRtIYh
privacy                                               PRIVATE
title                            zzz_seed_music_albums Part 6
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                903


**************************************** (223/252) Playlist: zzz_seed_music_albums Part 7 ****************************************
                                                            0
id                         PLWptjpDqazOxy3n0HO9hqyn-daFvzaNzm
privacy                                               PRIVATE
title                            zzz_seed_music_albums Part 7
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             6+ hours
trackCount                                                898


**************************************** (224/252) Playlist: zzz_seed_music_albums Part 8 ****************************************
                                                            0
id                         PLWptjpDqazOzQvGDUSSPAb9tA5FDZBPFI
privacy                                               PRIVATE
title                            zzz_seed_music_albums Part 8
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             5+ hours
trackCount                                                803


**************************************** (225/252) Playlist: zzz_seed_music_albums Part 9 ****************************************
                                                            0
id                         PLWptjpDqazOxMgc17Tk9HY5QRWwkzqvAe
privacy                                               PRIVATE
title                            zzz_seed_music_albums Part 9
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                948


**************************************** (226/252) Playlist: zzz_seed_music_albums_uploaded_flac ****************************************
                                                            0
id                         PLWptjpDqazOxB-dnkSFOWwZPlPW_f9OsM
privacy                                               PRIVATE
title                     zzz_seed_music_albums_uploaded_flac
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                            10+ hours
trackCount                                                217


**************************************** (227/252) Playlist: zzz_seed_stuck_in_head_albums ****************************************
                                                            0
id                         PLWptjpDqazOw29AtnCtXQgQOxV9TjSNnS
privacy                                               PRIVATE
title                           zzz_seed_stuck_in_head_albums
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                340


**************************************** (228/252) Playlist: zzz_upload_albums Part 1 ****************************************
                                                            0
id                         PLWptjpDqazOxNZrH-Gdpg2Z9plqeyMc7Q
privacy                                               PRIVATE
title                                zzz_upload_albums Part 1
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             5+ hours
trackCount                                                382


**************************************** (229/252) Playlist: zzzz_2005s ****************************************
                                                            0
id                         PLWptjpDqazOyKyQqempLZfqdAt83a4ZZM
privacy                                               PRIVATE
title                                              zzzz_2005s
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             5+ hours
trackCount                                                264


**************************************** (230/252) Playlist: zzzz_2010 ****************************************
                                                            0
id                         PLWptjpDqazOw4RWUiVLBXalBoqQAiHaAK
privacy                                               PRIVATE
title                                               zzzz_2010
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                  5 hours, 46 minutes
trackCount                                                 93


**************************************** (231/252) Playlist: zzzz_2011 ****************************************
                                                            0
id                         PLWptjpDqazOyMwByfnT-HK_53RBk1y824
privacy                                               PRIVATE
title                                               zzzz_2011
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                  7 hours, 58 minutes
trackCount                                                 98


**************************************** (232/252) Playlist: zzzz_2012 ****************************************
                                                            0
id                         PLWptjpDqazOyWolDmVuQMIvLfE6y6a81w
privacy                                               PRIVATE
title                                               zzzz_2012
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                123


**************************************** (233/252) Playlist: zzzz_2013 ****************************************
                                                            0
id                         PLWptjpDqazOx4g-do8dFts9LClhd428E5
privacy                                               PRIVATE
title                                               zzzz_2013
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             6+ hours
trackCount                                                164


**************************************** (234/252) Playlist: zzzz_2014 ****************************************
                                                            0
id                         PLWptjpDqazOyZPO6gsjCnSWqlw7xUJ5BO
privacy                                               PRIVATE
title                                               zzzz_2014
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                  4 hours, 51 minutes
trackCount                                                 76


**************************************** (235/252) Playlist: zzzz_2015 ****************************************
                                                            0
id                         PLWptjpDqazOzHFiE4WSkDfqdFiiTQNUM1
privacy                                               PRIVATE
title                                               zzzz_2015
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                  4 hours, 11 minutes
trackCount                                                 75


**************************************** (236/252) Playlist: zzzz_2017 ****************************************
                                                            0
id                         PLWptjpDqazOycGZkkgSj3O-VkzJFMGCKT
privacy                                               PRIVATE
title                                               zzzz_2017
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                           56 minutes
trackCount                                                 18


**************************************** (237/252) Playlist: zzzz_50s_older ****************************************
                                                            0
id                         PLWptjpDqazOxMnrquiPXPah2qtfDCANse
privacy                                               PRIVATE
title                                          zzzz_50s_older
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                   2 hours, 6 minutes
trackCount                                                 10


**************************************** (238/252) Playlist: zzzz_60s ****************************************
                                                            0
id                         PLWptjpDqazOyPJqCAuPce2ndOPHO8YNyj
privacy                                               PRIVATE
title                                                zzzz_60s
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                  2 hours, 46 minutes
trackCount                                                 43


**************************************** (239/252) Playlist: zzzz_70s ****************************************
                                                            0
id                         PLWptjpDqazOykbv_0KfMd9nln2dHQd7aX
privacy                                               PRIVATE
title                                                zzzz_70s
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                152


**************************************** (240/252) Playlist: zzzz_80s ****************************************
                                                            0
id                         PLWptjpDqazOyxEvceE2nLObt2t3_w-IiT
privacy                                               PRIVATE
title                                                zzzz_80s
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                  5 hours, 52 minutes
trackCount                                                 81


**************************************** (241/252) Playlist: zzzz_90s ****************************************
                                                            0
id                         PLWptjpDqazOy0mb52MZrd51Gh7O5OGTO-
privacy                                               PRIVATE
title                                                zzzz_90s
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                199


**************************************** (242/252) Playlist: zzzz_all ****************************************
                                                            0
id                         PLWptjpDqazOxlX0jt48aUymMahwgdxFnF
privacy                                               PRIVATE
title                                                zzzz_all
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             5+ hours
trackCount                                                527


**************************************** (243/252) Playlist: zzzz_all 1 ****************************************
                                                            0
id                         PLWptjpDqazOwjq56JO2cLDarDdkTWhgz6
privacy                                               PRIVATE
title                                              zzzz_all 1
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             6+ hours
trackCount                                                707


**************************************** (244/252) Playlist: zzzz_all 2 ****************************************
                                                            0
id                         PLWptjpDqazOzq21hhMES9CvXCG4Qd6UqG
privacy                                               PRIVATE
title                                              zzzz_all 2
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             9+ hours
trackCount                                                256


**************************************** (245/252) Playlist: zzzz_all 3 ****************************************
                                                            0
id                         PLWptjpDqazOzk8vHf7UJTCPiTxozlnKx8
privacy                                               PRIVATE
title                                              zzzz_all 3
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             4+ hours
trackCount                                                713


**************************************** (246/252) Playlist: zzzz_all 4 ****************************************
                                                            0
id                         PLWptjpDqazOzcW6cx9y6nXoRosR00bDDh
privacy                                               PRIVATE
title                                              zzzz_all 4
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             6+ hours
trackCount                                                703


**************************************** (247/252) Playlist: zzzz_all 5 ****************************************
                                                            0
id                         PLWptjpDqazOwV4bhGoeiKGXMa9PCKTzMA
privacy                                               PRIVATE
title                                              zzzz_all 5
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             6+ hours
trackCount                                                665


**************************************** (248/252) Playlist: zzzz_all 6 ****************************************
                                                            0
id                         PLWptjpDqazOyh08tZjD0SBzQbehN2PGrC
privacy                                               PRIVATE
title                                              zzzz_all 6
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             5+ hours
trackCount                                                661


**************************************** (249/252) Playlist: zzzz_thumbs_down ****************************************
                                                            0
id                         PLWptjpDqazOwUz2ci9ZEivIJ_4dNVx9v-
privacy                                               PRIVATE
title                                        zzzz_thumbs_down
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                           47 minutes
trackCount                                                 14


**************************************** (250/252) Playlist: zzzz_thumbs_down 1 ****************************************
                                                            0
id                         PLWptjpDqazOxj8cjCK6wF1KzhG1mT94vs
privacy                                               PRIVATE
title                                      zzzz_thumbs_down 1
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                           51 minutes
trackCount                                                 14


**************************************** (251/252) Playlist: zzzz_thumbs_up ****************************************
                                                            0
id                         PLWptjpDqazOwbnb0x7ecV_RZWxJToctaF
privacy                                               PRIVATE
title                                          zzzz_thumbs_up
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                547


**************************************** (252/252) Playlist: zzzz_thumbs_up 1 ****************************************
                                                            0
id                         PLWptjpDqazOwobQdOQliW2IllkDxAKeU-
privacy                                               PRIVATE
title                                        zzzz_thumbs_up 1
author      {'name': 'Jake G', 'id': 'UCDvJYHQoKPhpF-sGFUM...
duration                                             7+ hours
trackCount                                                449
Wall time: 1min 42s